const nodemailer = require('nodemailer');
const fs = require('fs');
const path = require('path');

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: 'rei.deepthought@gmail.com',
    pass: 'xlgl psng hqvp rxfx'
  }
});

const dashboardPath = path.join(__dirname, 'dashboard.png');
const imageData = fs.readFileSync(dashboardPath).toString('base64');

const mailOptions = {
  from: '"Rei 🌟" <rei.deepthought@gmail.com>',
  to: 'NorikoKubo12@gmail.com',
  subject: '📊 Warren\'s Health Dashboard — Apr 13–20, 2026',
  html: `
    <div style="font-family: sans-serif; max-width: 700px; margin: 0 auto; background: #1a1a2e; color: #eee; padding: 30px; border-radius: 12px;">
      <h2 style="color: #1abc9c; margin-top: 0;">📊 Warren's Health Dashboard</h2>
      <p style="color: #aaa;">April 13–20, 2026 · Generated by Rei</p>
      
      <img src="cid:dashboard" style="width: 100%; border-radius: 8px; margin: 20px 0;" />
      
      <h3 style="color: #e0e0e0;">Week Highlights</h3>
      <ul style="color: #ccc; line-height: 1.8;">
        <li>⚖️ <strong>Weight:</strong> 120.0 → 118.1 kg — down 1.9 kg in 8 days</li>
        <li>🍗 <strong>Protein:</strong> Strong most days — Apr 18 tournament day was the weak spot</li>
        <li>🍬 <strong>Sugar:</strong> Generally controlled — Apr 18 DQ sundae was the big outlier</li>
        <li>🥦 <strong>Fibre:</strong> Consistently below 25g target — psyllium husk now part of routine</li>
        <li>🔥 <strong>Calories:</strong> Mostly on budget — Apr 14 was the big day at 2,555 kcal</li>
        <li>🏒 <strong>Tournament weekend:</strong> Apr 16–19 away from home — held up well overall</li>
      </ul>

      <p style="color: #888; font-size: 13px; margin-top: 30px; border-top: 1px solid #333; padding-top: 16px;">
        Apr 20 is still in progress — bars will look low for that day.<br/>
        Sent by Rei · rei.deepthought@gmail.com
      </p>
    </div>
  `,
  attachments: [{
    filename: 'health-dashboard.png',
    content: imageData,
    encoding: 'base64',
    cid: 'dashboard'
  }]
};

transporter.sendMail(mailOptions, (err, info) => {
  if (err) {
    console.error('Error:', err);
    process.exit(1);
  } else {
    console.log('Sent:', info.messageId);
  }
});
